### ISSUE TITLE
Route53 Support

### ISSUE THREAD

**Issue by barrynorman** [4ALLPORTAL/helm-charts#31]
Hello there! 

thanks for sharing the helm charts. ;)
I wanted to ask kindle for Route53 Support.

**Comment by barrynorman** [comment]
In order to support this feature as far as I understand I need to be able to pass the following parameter: 
`
serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn: {var.XXXYYY}
serviceAccount.name: {var.NAME}
securityContext.fsGroup.enabled: true
securityContext.fsGroup: 1001
serviceAccount.create: true
`

**Comment by mstroecker** [comment]
Please read here: https://github.com/4ALLPORTAL/helm-charts/pull/32#issuecomment-1327490858
